name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # ينشئ مجلد android تلقائيًا ويحافظ على main.dart حقك
      - name: Generate Flutter project
        run: |
          cp lib/main.dart /tmp/main.dart
          flutter create --platforms=android --project-name hack_sim .
          cp /tmp/main.dart lib/main.dart

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: hack-sim-apk
          path: build/app/outputs/flutter-apk/app-release.apk
